body:
  - type: markdown
    attributes:
      value: |
        # 💡 Feature Request

        Thank you for taking the time to suggest a feature! Please fill out this form as completely as possible.

        Before submitting, please check:
        - [ ] Search existing discussions and issues
        - [ ] Check if this feature already exists
        - [ ] Consider if this should be a configuration option vs. core functionality

  - type: textarea
    attributes:
      label: 🎯 Problem Statement
      description: What problem are you trying to solve? What pain point does this address?
      placeholder: |
        I'm currently struggling with X because Y. This makes it difficult to Z.
    validations:
      required: true

  - type: textarea
    attributes:
      label: 💡 Proposed Solution
      description: Describe the feature you'd like to see implemented.
      placeholder: |
        I propose adding a new function `createLogger()` that accepts custom configurations...
    validations:
      required: true

  - type: textarea
    attributes:
      label: 💻 Example Usage
      description: Show how you would like to use this feature with code examples.
      placeholder: |
        ```typescript
        const logger = createLogger({
          component: 'my-service',
          customOption: true
        });
        logger.info('Hello World');
        ```
    validations:
      required: false

  - type: textarea
    attributes:
      label: 🔄 Alternatives Considered
      description: What alternatives have you considered? Why are they not sufficient?
      placeholder: |
        I tried using console.log, but it lacks structured logging and production support...

  - type: textarea
    attributes:
      label: 📋 Additional Context
      description: Add any other context, screenshots, or links to related discussions.
      placeholder: |
        This would be similar to the logging system in [link to example]...
        Related issue: #123
