import type { FormMetadata } from '@workspace/types';

export const comprehensiveTestFormMetadata: FormMetadata = {
  version: '1.0.0',
  fields: [
    // 基本信息 - Text 类型
    {
      id: 'fullName',
      name: 'fullName',
      type: 'text',
      label: '姓名',
      placeholder: '请输入您的真实姓名',
      required: true,
    },
    {
      id: 'email',
      name: 'email',
      type: 'text',
      label: '邮箱地址',
      placeholder: '请输入您的邮箱地址',
      required: true,
    },
    {
      id: 'phone',
      name: 'phone',
      type: 'text',
      label: '手机号码',
      placeholder: '请输入您的手机号码',
      required: false,
    },

    // 数字信息 - Number 类型
    {
      id: 'age',
      name: 'age',
      type: 'number',
      label: '年龄',
      placeholder: '请输入您的年龄',
      required: true,
    },
    {
      id: 'experience',
      name: 'experience',
      type: 'number',
      label: '工作经验（年）',
      placeholder: '请输入您的工作年限',
      required: false,
    },
    {
      id: 'salary',
      name: 'salary',
      type: 'number',
      label: '期望薪资（千元）',
      placeholder: '请输入您的期望月薪（千元）',
      required: false,
    },

    // 选择信息 - Select 类型
    {
      id: 'department',
      name: 'department',
      type: 'select',
      label: '申请部门',
      placeholder: '请选择您申请的部门',
      required: true,
      options: [
        { label: '技术部', value: 'tech' },
        { label: '产品部', value: 'product' },
        { label: '设计部', value: 'design' },
        { label: '市场部', value: 'marketing' },
        { label: '销售部', value: 'sales' },
        { label: '人力资源部', value: 'hr' },
      ],
    },
    {
      id: 'position',
      name: 'position',
      type: 'select',
      label: '申请职位',
      placeholder: '请选择您申请的职位',
      required: true,
      options: [
        { label: '初级工程师', value: 'junior' },
        { label: '中级工程师', value: 'middle' },
        { label: '高级工程师', value: 'senior' },
        { label: '技术专家', value: 'expert' },
        { label: '团队经理', value: 'manager' },
        { label: '总监', value: 'director' },
      ],
    },
    {
      id: 'education',
      name: 'education',
      type: 'select',
      label: '最高学历',
      placeholder: '请选择您的最高学历',
      required: false,
      options: [
        { label: '高中', value: 'high_school' },
        { label: '大专', value: 'college' },
        { label: '本科', value: 'bachelor' },
        { label: '硕士', value: 'master' },
        { label: '博士', value: 'phd' },
      ],
    },

    // 详细描述 - Textarea 类型
    {
      id: 'introduction',
      name: 'introduction',
      type: 'textarea',
      label: '个人简介',
      placeholder: '请简要介绍您的个人背景和专业技能',
      required: true,
    },
    {
      id: 'experience',
      name: 'experience',
      type: 'textarea',
      label: '工作经验',
      placeholder: '请详细描述您的工作经历和项目经验',
      required: false,
    },
    {
      id: 'motivation',
      name: 'motivation',
      type: 'textarea',
      label: '申请动机',
      placeholder: '请描述您为什么希望加入我们公司',
      required: false,
    },

    // 同意选项 - Checkbox 类型
    {
      id: 'termsAccepted',
      name: 'termsAccepted',
      type: 'checkbox',
      label: '我同意公司的服务条款和隐私政策',
      placeholder: '阅读并同意相关条款',
      required: true,
      defaultValue: false,
    },
    {
      id: 'marketingAccepted',
      name: 'marketingAccepted',
      type: 'checkbox',
      label: '我同意接收公司的营销信息',
      placeholder: '接收产品更新和优惠信息',
      required: false,
      defaultValue: false,
    },
    {
      id: 'backgroundCheck',
      name: 'backgroundCheck',
      type: 'checkbox',
      label: '我同意进行背景调查',
      placeholder: '用于核实提供的信息',
      required: false,
      defaultValue: false,
      condition: {
        fieldId: 'termsAccepted',
        operator: 'equals',
        value: true,
      },
    },

    // 日期信息 - Date 类型
    {
      id: 'availableDate',
      name: 'availableDate',
      type: 'date',
      label: '可入职日期',
      placeholder: '请选择您可入职的日期',
      required: false,
    },
    {
      id: 'birthDate',
      name: 'birthDate',
      type: 'date',
      label: '出生日期',
      placeholder: '请选择您的出生日期',
      required: false,
      condition: {
        fieldId: 'age',
        operator: 'greater_than',
        value: 18,
      },
    },
    {
      id: 'graduationDate',
      name: 'graduationDate',
      type: 'date',
      label: '毕业日期',
      placeholder: '请选择您的毕业日期',
      required: false,
      condition: {
        fieldId: 'education',
        operator: 'not_empty',
        value: true,
      },
    },

    // 技能评估 - 条件逻辑字段
    {
      id: 'hasPortfolio',
      name: 'hasPortfolio',
      type: 'checkbox',
      label: '我有作品集可以展示',
      placeholder: '包含设计作品、项目案例等',
      required: false,
      defaultValue: false,
      condition: {
        fieldId: 'department',
        operator: 'equals',
        value: 'design',
      },
    },
    {
      id: 'portfolioUrl',
      name: 'portfolioUrl',
      type: 'text',
      label: '作品集链接',
      placeholder: '请提供您的在线作品集链接',
      required: false,
      condition: {
        fieldId: 'hasPortfolio',
        operator: 'equals',
        value: true,
      },
    },
    {
      id: 'githubUrl',
      name: 'githubUrl',
      type: 'text',
      label: 'GitHub 链接',
      placeholder: '请提供您的 GitHub 主页链接',
      required: false,
      condition: {
        fieldId: 'department',
        operator: 'equals',
        value: 'tech',
      },
    },
    {
      id: 'referralSource',
      name: 'referralSource',
      type: 'select',
      label: '了解渠道',
      placeholder: '您是如何了解我们公司的？',
      required: false,
      options: [
        { label: '招聘网站', value: 'job_board' },
        { label: '社交媒体', value: 'social_media' },
        { label: '朋友推荐', value: 'friend_referral' },
        { label: '公司官网', value: 'company_website' },
        { label: '新闻媒体', value: 'news' },
        { label: '其他', value: 'other' },
      ],
    },
    {
      id: 'referralName',
      name: 'referralName',
      type: 'text',
      label: '推荐人姓名',
      placeholder: '请输入推荐人的姓名',
      required: false,
      condition: {
        fieldId: 'referralSource',
        operator: 'equals',
        value: 'friend_referral',
      },
    },

    // 附加信息
    {
      id: 'expectedSalary',
      name: 'expectedSalary',
      type: 'number',
      label: '期望薪资（月）',
      placeholder: '请输入您的期望月薪',
      required: false,
      condition: {
        fieldId: 'position',
        operator: 'not_equals',
        value: 'intern',
      },
    },
    {
      id: 'willingToRelocate',
      name: 'willingToRelocate',
      type: 'checkbox',
      label: '我愿意为了工作地点搬迁',
      placeholder: '如工作地点需要，可以搬迁',
      required: false,
      defaultValue: false,
    },
    {
      id: 'workLocation',
      name: 'workLocation',
      type: 'select',
      label: '期望工作地点',
      placeholder: '请选择您期望的工作地点',
      required: false,
      options: [
        { label: '北京', value: 'beijing' },
        { label: '上海', value: 'shanghai' },
        { label: '广州', value: 'guangzhou' },
        { label: '深圳', value: 'shenzhen' },
        { label: '杭州', value: 'hangzhou' },
        { label: '成都', value: 'chengdu' },
        { label: '远程办公', value: 'remote' },
      ],
      condition: {
        fieldId: 'willingToRelocate',
        operator: 'equals',
        value: true,
      },
    },
  ],
};

// 简化版本的测试表单
export const simpleTestFormMetadata: FormMetadata = {
  version: '1.0.0',
  fields: [
    {
      id: 'name',
      name: 'name',
      type: 'text',
      label: '姓名',
      placeholder: '请输入您的姓名',
      required: true,
    },
    {
      id: 'email',
      name: 'email',
      type: 'text',
      label: '邮箱',
      placeholder: '请输入您的邮箱',
      required: true,
    },
    {
      id: 'age',
      name: 'age',
      type: 'number',
      label: '年龄',
      placeholder: '请输入您的年龄',
      required: true,
    },
    {
      id: 'gender',
      name: 'gender',
      type: 'select',
      label: '性别',
      placeholder: '请选择性别',
      required: true,
      options: [
        { label: '男', value: 'male' },
        { label: '女', value: 'female' },
        { label: '其他', value: 'other' },
      ],
    },
    {
      id: 'interests',
      name: 'interests',
      type: 'textarea',
      label: '兴趣爱好',
      placeholder: '请描述您的兴趣爱好',
      required: false,
    },
    {
      id: 'newsletter',
      name: 'newsletter',
      type: 'checkbox',
      label: '订阅我们的新闻通讯',
      placeholder: '接收最新的资讯和更新',
      required: false,
      defaultValue: false,
    },
  ],
};