name: 🐞 Bug Report
description: Create a bug report to help us improve
title: "bug: "
labels: ["🐞❔ unconfirmed bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before creating a new issue, please search existing issues to avoid duplicates.

  - type: textarea
    attributes:
      label: Environment Information
      description: |
        Run this command in your project root and paste the results in a code block:
        ```bash
        node --version && pnpm --version && pnpm list --depth=0
        ```
      placeholder: |
        Node.js: v22.20.0
        pnpm: 10.15.1
        @fastbuild/logger: 1.0.0
        ... other packages ...
    validations:
      required: true

  - type: textarea
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is, and what you expected to happen.
      placeholder: |
        When I run `pnpm build`, I expected the build to succeed, but instead I get a TypeScript error.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior. Include code snippets, commands, or file contents.
      placeholder: |
        1. Run `pnpm install`
        2. Execute `pnpm build`
        3. See error message
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      description: What you expected to happen.
      placeholder: The build should complete successfully without TypeScript errors.

  - type: textarea
    attributes:
      label: Actual Behavior
      description: What actually happened. Include error messages, stack traces, or screenshots.
      placeholder: |
        Error: TypeScript compilation failed
        src/components/Button.tsx:10:5 - Type 'string' is not assignable to type 'number'

  - type: textarea
    attributes:
      label: Additional Context
      description: Add any other context about the problem here, such as logs, screenshots, or related issues.
