contact_links:
  - name: 📚 Documentation
    url: https://github.com/[YOUR_ORG]/[YOUR_REPO]/discussions
    about: Check documentation and discussions first
  - name: 💬 Ask a question
    url: https://github.com/[YOUR_ORG]/[YOUR_REPO]/discussions/new?category=q-a
    about: Ask questions and discuss with other community members
  - name: 💡 Feature request
    url: https://github.com/[YOUR_ORG]/[YOUR_REPO]/discussions/new?category=ideas
    about: Suggest new features and improvements
